### PR TITLE
html format

### PR DESCRIPTION
**Pull request by moabi**
single element is structured with div and ul list
each shortcode has a specific class
eg : wpg-issue for single issue shortcode

### CODE REVIEW

**Comment by moabi** [comment]
I just saw you push it to wp repo, thank you !
one point : it is compatible with wp 4.4

As I told you, if you don't have the time, add me to the wp repo (as I understand you're not active on this project anymore and you don't want to spend time on it which is totally normal)...

**Comment by moabi** [comment]
I added a tinymce button to help inserting the shortcode
Updated the wordpress readme (sorry I never had to do that before)

**Comment by bretonics** [comment]
@moabi I noticed you haven't been added to the WP repo but you have continued development. Do you know what the status of this is, any plans?

**Comment by moabi** [comment]
@bretonics don't have any news right now
Last push request did not get merged neither..
@seinoxygen any update on your side ?
Shall you state your repo as deprecated ? Or add me to it...as you like

**Comment by seinoxygen** [comment]
I'm trying to merge but it has conflicts and its out of sync... Will be trying to do it today if its possible.

**Comment by seinoxygen** [comment]
Btw @moabi I've granted you access to commit directly to this repo also to wordpress svn.

**Pull request merged**
