### PR TITLE
Change API call and fix 'issues' call

### LINKED ISSUE #17: Issues List error: 404
There's an error on the "issues" request made through the API. The structure looks right according to the API, but I'm not sure why it's not working...did it change?

### PR DESCRIPTION
**Pull request by bretonics**
This addresses and closes #17 by changing the API call for issues to `user/issues?state=all&filter=all` and using a personal access token rather than creating a "developer app", which seems unnecessary to use a client/secret ID.

### CODE REVIEW

**Comment by bretonics** [comment]
@moabi any updates on this?

**Comment by moabi** [comment]
Hi, 
I added the access token, client/secret ID is still available, and can be choosen over the token access.
I also updated the call for issues, 
please check if it fits your needs, 
thanks

**Comment by moabi** [comment]
@bretonics any news ?!

**Comment by bretonics** [comment]
@moabi I briefly looked it over after pulling your changes, but something seems wrong. After the new commits it results in a blank page when reloading. Haven't had much time to check what it is, does this happen to you?

Also, I didn't see any of the commit changes in this pull request incorporated into your new version and these work for me (though I see you added the access token)...

I'll look over it again this weekend. Maybe the blank page is just me, but more importantly I don't see the `issues` API call issue #17 addressed (commit `732a710`)

**Comment by moabi** [comment]
ok, the issue is if you don't fill repository, it will take the default (eg: wp-github) which will cause a 404, 
this should be fixed, in the instructions, now : 

List last 10 commits from all repositories:

`[github-commits username="seinoxygen" repository="" limit="10"]`

**Comment by bretonics** [comment]
Hmm, I see, well I guess the best thing to do is make the default `""` rather than `wp-github`....which I see you added in your [last commit] (https://github.com/seinoxygen/wp-github/commit/780f5dbbe884204417474abb3f85d6224d5f40b8) if I am not mistaken.

**Pull request closed without merging**
